spring:
  cloud:
    gateway:
      routes:
        - id: get_route
          uri: http://localhost:9999/get
          predicates:
            - Path=/get
        - id: post_route
          uri: http://localhost:9999/post
          predicates:
            - Path=/post
  cache:
    type: hazelcast

rate-limiter:
  costs:
    - path: /get
      cost: 2
    - path: /get
      cost: 1
    - path: /post
      cost: 5
  limiters:
    - capacity: 10
      period: 1m
      name: limiter1
    - capacity: 300
      period: 1h
      name: limiter2
management:
  endpoints:
    web:
      exposure:
        include: "*"

rate-limit:
  enabled: "True"